---
# Enable REST APIs for Jetport

- name: install uwsgi
  pip: name=uwsgi state=present
  
- name: install nginx site config (template)
  template: src=sites-nginx.conf.template dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: create/verify uwsgi vassal directory
  file: path=/etc/uwsgi/vassals state=directory

- name: copy uwsgi emperor config to config directory
  copy: src=emperor.ini dest=/etc/uwsgi/emperor.ini
  
- name: copy configs for vassals managed by emperor
  copy: src={{ item }} dest=/etc/uwsgi/vassals/{{ item }}
  with_items:
    - uwsgi-jetport.ini
    - uwsgi-jetport-sim.ini

- name: copy uwsgi configuration for starting emperor
  copy: src=uwsgi.conf dest=/etc/init/uwsgi.conf
  
- name: start uwsgi
  service: name=uwsgi state=started