---
# Initialize Jetport environment

- name: create/verify project root directory
  file: owner={{ project_name }} group={{ project_name }} mode=755 path={{ project_root }} state=directory

- name: create/verify project source directory
  file: owner={{ project_name }} group={{ project_name }} mode=755 path="{{ project_root }}/{{ project_name }}" state=directory

- name: pull source from repo
  sudo: yes
  sudo_user: "{{ project_name }}"
  git: repo={{ project_repo }} dest="{{ project_root }}/{{ project_name }}" accept_hostkey=yes

- name: install tox and pbr
  pip: name={{ item }} state=present virtualenv={{ project_root }} virtualenv_command=virtualenv-2.7 extra_args='-U'
  with_items:
    - pbr
    - tox

- name: install project defined requirements
  pip: state=present requirements="{{ project_root }}/{{ project_name }}/requirements.txt" virtualenv={{ project_root }} virtualenv_command=virtualenv-2.7 extra_args='-U'

- name: install jetport
  pip: state=present virtualenv={{ project_root }} virtualenv_command=virtualenv-2.7 name="{{ project_root }}/{{ project_name }}"

- name: set owner and group of virtualenv directories
  file: owner={{ project_name }} group={{ project_name }} mode=755 recurse=yes path="{{ project_root }}/{{ item }}" state=directory
  with_items:
    - bin
    - etc
    - include
    - lib
    - local

- name: copy local conf to jetport.conf
  copy: src="{{ project_root }}/etc/{{ project_name }}/{{ project_name }}-local.conf" dest="{{ project_root }}/etc/{{ project_name }}/{{ project_name }}.conf"
    
- name: configure jetport to use localhost mongodb
  lineinfile: dest="{{ project_root }}/etc/{{ project_name }}/{{ project_name }}.conf" regexp="^connection=mongodb" line="connection=mongodb://localhost/local" state=present

- name: create symlink in root level /etc directory
  file: src="{{ project_root }}/etc/{{ project_name }}" dest="/etc/{{ project_name }}" state=link

- name: make web documentation directories
  file: owner="www-data" group="www-data" mode=755 recurse=yes path=/var/www/html/docs/cover state=directory
