---
# create project user and associated components

- name: Create user
  user: home="/home/{{ project_name }}" name={{ project_name }} password={{ user_password }} groups=admin append=yes state=present

- name: make .ssh directory
  file: path="/home/{{ project_name }}/.ssh" group={{ project_name }} owner={{ project_name }} state=directory

- name: Add SSH private key
  copy: src=id_rsa dest="/home/{{ project_name }}/.ssh/id_rsa" group={{ project_name }} owner={{ project_name }} mode=600
  
- name: Add SSH pub key
  copy: src=id_rsa.pub dest="/home/{{ project_name }}/.ssh/id_rsa.pub" group={{ project_name }} owner={{ project_name }}
