---
# Playbook for MongoDB (simple)

- name: add mongodb repo gpg key
  apt_key: url=http://docs.mongodb.org/10gen-gpg-key.asc state=present

- name: add mongodb offical apt repository
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present

- name: install mongodb
  apt: pkg=mongodb-org state=installed force=yes

- name: configure mongodb process mongod
  copy: src=mongod.conf dest=/etc/mongod.conf
  notify: restart mongod
