---
# Install packages

- name: install packages
  apt: pkg={{ item }} state=present
  with_items:
    - gcc
    - python-dev
    - git
    - python-pip

- name: install external python packages
  pip: name={{ item }} state=present
  with_items:
    - virtualenv
    - ansible

