---
# Playbook for installing RabbitMQ

- name: add rabbitmq repo gpg key
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: add rabbitmq official apt repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: install rabbitmq
  apt: pkg=rabbitmq-server state=installed force=yes

- name: enable rabbitmq plugins
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  notify: restart rabbitmq

- name: make guest user accessible from host
  copy: src=rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq

