---
# Install packages

- name: install packages
  apt: pkg={{ item }} state=present
  with_items:
    - gcc
    - python-devel
    - git
    
- name: install pip
  easy_install: name=pip
  
- name: install ansible
  pip: name=ansible state=present
